// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gda_codes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGDACode = `-- name: CreateGDACode :one
INSERT INTO gda_codes (code, person_id, user_id)
VALUES ($1, $2, $3)
RETURNING code, person_id, user_id, created_at
`

type CreateGDACodeParams struct {
	Code     string      `json:"code"`
	PersonID pgtype.UUID `json:"person_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Persists a freshly generated GDA code bound to (person_id, user_id).
// The canonical 12-character (no hyphens, uppercase) form is stored.
func (q *Queries) CreateGDACode(ctx context.Context, arg CreateGDACodeParams) (GdaCode, error) {
	row := q.db.QueryRow(ctx, createGDACode, arg.Code, arg.PersonID, arg.UserID)
	var i GdaCode
	err := row.Scan(
		&i.Code,
		&i.PersonID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGDACode = `-- name: DeleteGDACode :exec
DELETE FROM gda_codes
WHERE code = $1 AND user_id = $2
`

type DeleteGDACodeParams struct {
	Code   string      `json:"code"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGDACode(ctx context.Context, arg DeleteGDACodeParams) error {
	_, err := q.db.Exec(ctx, deleteGDACode, arg.Code, arg.UserID)
	return err
}

const getGDACodeByCode = `-- name: GetGDACodeByCode :one
SELECT code, person_id, user_id, created_at FROM gda_codes
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetGDACodeByCode(ctx context.Context, code string) (GdaCode, error) {
	row := q.db.QueryRow(ctx, getGDACodeByCode, code)
	var i GdaCode
	err := row.Scan(
		&i.Code,
		&i.PersonID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listGDACodesByPersonID = `-- name: ListGDACodesByPersonID :many
SELECT code, person_id, user_id, created_at FROM gda_codes
WHERE person_id = $1 AND user_id = $2
ORDER BY created_at ASC
`

type ListGDACodesByPersonIDParams struct {
	PersonID pgtype.UUID `json:"person_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListGDACodesByPersonID(ctx context.Context, arg ListGDACodesByPersonIDParams) ([]GdaCode, error) {
	rows, err := q.db.Query(ctx, listGDACodesByPersonID, arg.PersonID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GdaCode{}
	for rows.Next() {
		var i GdaCode
		if err := rows.Scan(
			&i.Code,
			&i.PersonID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGDACodesByUserID = `-- name: ListGDACodesByUserID :many
SELECT code, person_id, user_id, created_at FROM gda_codes
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListGDACodesByUserID(ctx context.Context, userID pgtype.UUID) ([]GdaCode, error) {
	rows, err := q.db.Query(ctx, listGDACodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GdaCode{}
	for rows.Next() {
		var i GdaCode
		if err := rows.Scan(
			&i.Code,
			&i.PersonID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
