// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GdaCode struct {
	Code      string             `json:"code"`
	PersonID  pgtype.UUID        `json:"person_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Person struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	EmailHash  []byte             `json:"email_hash"`
	Handle     pgtype.Text        `json:"handle"`
	KdfParams  []byte             `json:"kdf_params"`
	LoginHash  []byte             `json:"login_hash"`
	MfaEnabled bool               `json:"mfa_enabled"`
	MfaSecret  []byte             `json:"mfa_secret"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// Server-side Argon2id salt for login_hash
	LoginSalt []byte `json:"login_salt"`
}

type Vault struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Data      []byte             `json:"data"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
