// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persons.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

// Creates a minimal person row owned by the given user.
// All sensitive fields (name, addresses, phone, notes) live in the Vault (DECISION-052).
func (q *Queries) CreatePerson(ctx context.Context, userID pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, userID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons
WHERE id = $1 AND user_id = $2
`

type DeletePersonParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Deletes a person owned by the given user. Returns no rows; callers must check
// the affected row count to detect missing or foreign persons.
func (q *Queries) DeletePerson(ctx context.Context, arg DeletePersonParams) error {
	_, err := q.db.Exec(ctx, deletePerson, arg.ID, arg.UserID)
	return err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, user_id, created_at, updated_at FROM persons
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPersonByID(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPersonsByUserID = `-- name: ListPersonsByUserID :many
SELECT id, user_id, created_at, updated_at FROM persons
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPersonsByUserID(ctx context.Context, userID pgtype.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersonsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPerson = `-- name: TouchPerson :one
UPDATE persons
SET updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, created_at, updated_at
`

type TouchPersonParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Bumps updated_at (e.g. after vault rewrite affecting this person).
func (q *Queries) TouchPerson(ctx context.Context, arg TouchPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, touchPerson, arg.ID, arg.UserID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
