// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Persists a freshly generated GDA code bound to (person_id, user_id).
	// The canonical 12-character (no hyphens, uppercase) form is stored.
	CreateGDACode(ctx context.Context, arg CreateGDACodeParams) (GdaCode, error)
	// Creates a minimal person row owned by the given user.
	// All sensitive fields (name, addresses, phone, notes) live in the Vault (DECISION-052).
	CreatePerson(ctx context.Context, userID pgtype.UUID) (Person, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Persists a fresh share link. The id is generated by the handler (see
	// internal/handler/share.go) so that it is URL-safe and compact.
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	// Deletes rows whose expiration is older than the given cutoff. Used by
	// the (manual, for MVP) cleanup job per DECISION-056. Pass NOW() - 30 days
	// to retain the physical-deletion grace period.
	DeleteExpiredShareLinks(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteGDACode(ctx context.Context, arg DeleteGDACodeParams) error
	// Deletes a person owned by the given user. Returns no rows; callers must check
	// the affected row count to detect missing or foreign persons.
	DeletePerson(ctx context.Context, arg DeletePersonParams) error
	// Revokes a share link. Only the owning user is permitted to delete.
	DeleteShareLink(ctx context.Context, arg DeleteShareLinkParams) error
	GetGDACodeByCode(ctx context.Context, code string) (GdaCode, error)
	GetPersonByID(ctx context.Context, id pgtype.UUID) (Person, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	// Fetches a share link by its opaque id. Returns the row regardless of
	// expiration — the handler is responsible for enforcing the 410 Gone
	// behaviour so that expired links can still be diagnosed in logs.
	GetShareLinkByID(ctx context.Context, id string) (ShareLink, error)
	GetUserByEmailHash(ctx context.Context, emailHash []byte) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVaultByUserID(ctx context.Context, userID pgtype.UUID) (Vault, error)
	ListGDACodesByPersonID(ctx context.Context, arg ListGDACodesByPersonIDParams) ([]GdaCode, error)
	ListGDACodesByUserID(ctx context.Context, userID pgtype.UUID) ([]GdaCode, error)
	ListPersonsByUserID(ctx context.Context, userID pgtype.UUID) ([]Person, error)
	// Lists all share links owned by the given user, most recent first.
	// Exposed via GET /api/v1/share so the owner can audit or revoke links.
	ListShareLinksByUserID(ctx context.Context, userID pgtype.UUID) ([]ShareLink, error)
	// Bumps updated_at (e.g. after vault rewrite affecting this person).
	TouchPerson(ctx context.Context, arg TouchPersonParams) (Person, error)
	// Creates or updates the vault. On update, requires version match (optimistic locking, DECISION-051).
	// The version is incremented automatically.
	UpsertVault(ctx context.Context, arg UpsertVaultParams) (Vault, error)
}

var _ Querier = (*Queries)(nil)
