// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (id, user_id, ciphertext, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, ciphertext, expires_at, created_at
`

type CreateShareLinkParams struct {
	ID         string             `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Ciphertext []byte             `json:"ciphertext"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Persists a fresh share link. The id is generated by the handler (see
// internal/handler/share.go) so that it is URL-safe and compact.
func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.ID,
		arg.UserID,
		arg.Ciphertext,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredShareLinks = `-- name: DeleteExpiredShareLinks :exec
DELETE FROM share_links
WHERE expires_at < $1
`

// Deletes rows whose expiration is older than the given cutoff. Used by
// the (manual, for MVP) cleanup job per DECISION-056. Pass NOW() - 30 days
// to retain the physical-deletion grace period.
func (q *Queries) DeleteExpiredShareLinks(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredShareLinks, expiresAt)
	return err
}

const deleteShareLink = `-- name: DeleteShareLink :exec
DELETE FROM share_links
WHERE id = $1 AND user_id = $2
`

type DeleteShareLinkParams struct {
	ID     string      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Revokes a share link. Only the owning user is permitted to delete.
func (q *Queries) DeleteShareLink(ctx context.Context, arg DeleteShareLinkParams) error {
	_, err := q.db.Exec(ctx, deleteShareLink, arg.ID, arg.UserID)
	return err
}

const getShareLinkByID = `-- name: GetShareLinkByID :one
SELECT id, user_id, ciphertext, expires_at, created_at FROM share_links
WHERE id = $1
LIMIT 1
`

// Fetches a share link by its opaque id. Returns the row regardless of
// expiration — the handler is responsible for enforcing the 410 Gone
// behaviour so that expired links can still be diagnosed in logs.
func (q *Queries) GetShareLinkByID(ctx context.Context, id string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByID, id)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listShareLinksByUserID = `-- name: ListShareLinksByUserID :many
SELECT id, user_id, ciphertext, expires_at, created_at FROM share_links
WHERE user_id = $1
ORDER BY created_at DESC
`

// Lists all share links owned by the given user, most recent first.
// Exposed via GET /api/v1/share so the owner can audit or revoke links.
func (q *Queries) ListShareLinksByUserID(ctx context.Context, userID pgtype.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Ciphertext,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
