// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email_hash, kdf_params, login_hash, login_salt
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email_hash, handle, kdf_params, login_hash, mfa_enabled, mfa_secret, created_at, updated_at, login_salt
`

type CreateUserParams struct {
	EmailHash []byte `json:"email_hash"`
	KdfParams []byte `json:"kdf_params"`
	LoginHash []byte `json:"login_hash"`
	LoginSalt []byte `json:"login_salt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmailHash,
		arg.KdfParams,
		arg.LoginHash,
		arg.LoginSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.Handle,
		&i.KdfParams,
		&i.LoginHash,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginSalt,
	)
	return i, err
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, email_hash, handle, kdf_params, login_hash, mfa_enabled, mfa_secret, created_at, updated_at, login_salt FROM users
WHERE email_hash = $1
LIMIT 1
`

func (q *Queries) GetUserByEmailHash(ctx context.Context, emailHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailHash, emailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.Handle,
		&i.KdfParams,
		&i.LoginHash,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginSalt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email_hash, handle, kdf_params, login_hash, mfa_enabled, mfa_secret, created_at, updated_at, login_salt FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.Handle,
		&i.KdfParams,
		&i.LoginHash,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginSalt,
	)
	return i, err
}
