// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vaults.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVaultByUserID = `-- name: GetVaultByUserID :one
SELECT id, user_id, data, version, created_at, updated_at FROM vaults
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetVaultByUserID(ctx context.Context, userID pgtype.UUID) (Vault, error) {
	row := q.db.QueryRow(ctx, getVaultByUserID, userID)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVault = `-- name: UpsertVault :one
INSERT INTO vaults (user_id, data, version)
VALUES ($1, $2, 1)
ON CONFLICT (user_id)
DO UPDATE SET
    data = $2,
    version = vaults.version + 1
WHERE vaults.version = $3
RETURNING id, user_id, data, version, created_at, updated_at
`

type UpsertVaultParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Data    []byte      `json:"data"`
	Version int32       `json:"version"`
}

// Creates or updates the vault. On update, requires version match (optimistic locking, DECISION-051).
// The version is incremented automatically.
func (q *Queries) UpsertVault(ctx context.Context, arg UpsertVaultParams) (Vault, error) {
	row := q.db.QueryRow(ctx, upsertVault, arg.UserID, arg.Data, arg.Version)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
