-- name: CreateShareLink :one
-- Persists a fresh share link. The id is generated by the handler (see
-- internal/handler/share.go) so that it is URL-safe and compact.
INSERT INTO share_links (id, user_id, ciphertext, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING *;

-- name: GetShareLinkByID :one
-- Fetches a share link by its opaque id. Returns the row regardless of
-- expiration — the handler is responsible for enforcing the 410 Gone
-- behaviour so that expired links can still be diagnosed in logs.
SELECT * FROM share_links
WHERE id = $1
LIMIT 1;

-- name: DeleteShareLink :exec
-- Revokes a share link. Only the owning user is permitted to delete.
DELETE FROM share_links
WHERE id = $1 AND user_id = $2;

-- name: ListShareLinksByUserID :many
-- Lists all share links owned by the given user, most recent first.
-- Exposed via GET /api/v1/share so the owner can audit or revoke links.
SELECT * FROM share_links
WHERE user_id = $1
ORDER BY created_at DESC;

-- name: DeleteExpiredShareLinks :exec
-- Deletes rows whose expiration is older than the given cutoff. Used by
-- the (manual, for MVP) cleanup job per DECISION-056. Pass NOW() - 30 days
-- to retain the physical-deletion grace period.
DELETE FROM share_links
WHERE expires_at < $1;
